name: Playwright Tests
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm install
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run:  |
        SLACK_BOT_USER_OAUTH_TOKEN=${{ secrets.SLACK_TOKEN }} npx playwright test --reporter=list,json,html
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add path/to/generated/report.html  # Add only the report file
        git commit -m "Update HTML report"
        git push origin main
    
